### ISSUE TITLE
Mimic spawned but doesnt work

### ISSUE THREAD

**Issue by NathnDz** [x753/Lethal-Company-Mimics#21]
recently i play the mimic mod with my friends, but the mimic did spawn but it doesnt kill you after you interact with it (pressing E), rather, it simply enters a small pause before allowing you to interact with it once more, but the mimic does nothing.

i played with the newest version 2.6.0

**Comment by x753** [comment]
Might be another mod causing an incompatibility, do you have a list of mods you're using?

**Comment by Justl5** [comment]
Hello, I have the same problem. Here list of mods i'm using:
AinaVT-LethalConfig-1.4.2
Android_Official-ricardo-0.1.0
BeanCan-CustomDeathAudio-1.0.0
BepInEx-BepInExPack-5.4.2100
BunyaPineTree-ModelReplacementAPI-2.4.4
catobun-HornyHorn-0.0.1
Clementinise-CustomSounds-2.3.2
Coppertiel-MaskedEnemyOverhaulFork-3.3.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.15.1
femboytv-LethalPosters-1.2.3
FlipMods-TooManyEmotes-2.1.17
FoxGod-ThiccCompanyModelReplacement-2.0.1
jockie-LethalExpansionCore-1.3.15
JolimJostar-HighPolyThiccSuits_Fix_Plead-0.8.6
LeGrosRem-TheMaskAClownHorn-1.0.0
lolimaerated-Porsters-1.1.1
no00ob-LCSoundTool-1.5.1
Ozone-Runtime_Netcode_Patcher-0.2.5
Rattenbonkers-TVLoader-1.1.1
Rolandbox-Element_Of_Surprise_Land_Mine-1.0.5
Rolandbox-Moan_When_Hit-1.0.1
RugbugRedfern-Skinwalkers-5.0.0
Sligili-More_Emotes-1.3.3
Suskitech-AlwaysHearActiveWalkies-1.4.4
Thunderstruck-OnlyTheHelldiverModel-1.0.0
topongo-DootClownHorn-1.0.1
TwinDimensionalProductions-CoilHeadStare-1.0.9
x753-More_Suits-1.4.3
YourFurnace-ThickWomanSuit-1.0.0
Zaggy1024-OpenBodyCams-1.2.10
Zehs-ToilHead-1.3.5
APMods-KatanaScrap-0.2.0
Procyon-LootableLandmines-1.3.1
CommanderJoJo-ThiccCoilHead-1.2.2

And LogOutput:
[Info   :   BepInEx] Loading [Mimics 2.6.0]
[Warning: Unity Log] The script 'Mimics.MimicCollider' could not be instantiated!
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Mimics, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load list of method overrides due to Method not found: bool .IHittable.Hit(int,UnityEngine.Vector3,GameNetcodeStuff.PlayerControllerB,bool,int)
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_000D 
System.TypeLoadException: Could not load list of method overrides due to Method not found: bool .IHittable.Hit(int,UnityEngine.Vector3,GameNetcodeStuff.PlayerControllerB,bool,int)
[Info   :x753.Mimics] Plugin Mimics is loaded!!
[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load list of method overrides due to Method not found: bool .IHittable.Hit(int,UnityEngine.Vector3,GameNetcodeStuff.PlayerControllerB,bool,int)
Stack trace:
System.Reflection.Assembly.GetTypes () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
Mimics.Mimics.Awake () (at <87259d4760bd4e959a855338b66f4d08>:IL_0332)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

Thank you in advance

**Comment by NathnDz** [comment]
here are the list of mod i used, all of them are in the recent version, i struggle a lot combining the mods because of the v50 update, until now i still play in v49

BepInEx\plugins\CSync"
BepInEx\plugins\FacelessStalker"
BepInEx\plugins\InteractiveTerminalAPI"
"BepInEx\plugins\LethalBundles"
"BepInEx\plugins\LethalCompanyInputUtils"
"BepInEx\plugins\LethalConfig"
BepInEx\plugins\LethalLib"
BepInEx\plugins\LethalModDataLib"
BepInEx\plugins\LethalNetworkAPI"
BepInEx\plugins\LethalResonance"
BepInEx\plugins\LethalThings"
BepInEx\plugins\MMHOOK"
BepInEx\plugins\MoreCompanyCosmetics"
\BepInEx\plugins\MoreShipUpgrades"
BepInEx\plugins\Odin Serializer"
BepInEx\plugins\RollingGiant"
BepInEx\plugins\Scopophobia"
BepInEx\plugins\3270Fonts"
BepInEx\plugins\3270Fonts-LICENSE.txt"
BepInEx\plugins\bcm_assets"
BepInEx\plugins\bcm_customassets"
BepInEx\plugins\BrutalCompanyMinus.dll"
BepInEx\plugins\BrutalCompanyMinus.xml"
BepInEx\plugins\Coroner.dll"
BepInEx\plugins\CullFactory.dll"
BepInEx\plugins\CullFactory.pdb"
BepInEx\plugins\EladsHUD.dll"
BepInEx\plugins\EladsHUD.pdb"
BepInEx\plugins\Figgle.dll"
BepInEx\plugins\Figgle-LICENSE.txt"
BepInEx\plugins\GoAwayModList.dll"
BepInEx\plugins\HoldScanButton.dll"
BepInEx\plugins\immersivescraps.lem"
BepInEx\plugins\LateCompanyV1.0.13.dll"
BepInEx\plugins\LC_API.dll"
BepInEx\plugins\LCMaxSoundsFix.dll"
BepInEx\plugins\LethalLevelLoader.dll"
BepInEx\plugins\MaskedEnemyRework.dll"
BepInEx\plugins\me.loaforc.soundapi.dll"
BepInEx\plugins\menstalker_yaboiduckisnickerbar.dll"
BepInEx\plugins\Mirage.dll"
BepInEx\plugins\moonswept"
BepInEx\plugins\Moonswept.dll"
BepInEx\plugins\MoreCompany.dll"
BepInEx\plugins\mysterydice"
BepInEx\plugins\MysteryDice.dll"
BepInEx\plugins\OpenBodyCams.dll"
BepInEx\plugins\OpenMonitors.dll"
BepInEx\plugins\ReservedFlashlightSlot.dll"
BepInEx\plugins\ReservedItemSlotCore.dll"
BepInEx\plugins\ReservedWalkieSlot.dll"
BepInEx\plugins\schoolextra"
BepInEx\plugins\schoolmoon.dll"
BepInEx\plugins\ShipLootPlus.dll"
BepInEx\plugins\SkinwalkerMod.dll"
BepInEx\plugins\SurvivalBonus.dll"
BepInEx\plugins\TooManyEmotes.dll"
BepInEx\plugins\version"
BepInEx\plugins\yaboiduckimenstalkerassets"
BepInEx\plugins\YippeeMod.dll"
BepInEx\plugins\yippeesound"
BepInEx\plugins\Assets"
BepInEx\plugins\Bundles"
BepInEx\patchers\BepInEx.MonoMod.HookGenPatcher"
BepInEx\patchers\FixPluginTypesSerialization"
BepInEx\patchers\ShipLootPlusPreloader.dll"

**Comment by x753** [comment]
My mod was updated to v2.6.0 for the v50 update. You'll need to manually revert to v2.5.0 for compatibility with v49.

**Comment by NathnDz** [comment]
I've been playing your mod on v50 alongside the other mods I listed, but due to the bugs, I've given up playing on v50 and prefer to play on v49 instead.
