### ISSUE TITLE
Project configuration files missing from repo

### ISSUE THREAD

**Issue by EliteMasterEric** [x753/Lethal-Company-Mimics#22]
I'm trying to compile the mod on my local machine in order to make a pull request for it, however since it is missing the SLN and CSPROJ files I am struggling to get it to compile correctly (specifically with getting it to recognize the asset bundle resource).

**Comment by x753** [comment]
Should be as simple as dropping mimicdoor in Project > Properties > Resources 
![image](https://github.com/user-attachments/assets/8a17fdec-4fc2-47cb-8fa8-69c541a128c8)

Also make sure you have and run [NetcodePatcher.Cli.exe](https://github.com/EvaisaDev/UnityNetcodePatcher)

I don't want to include the project files because they're hacky and would only work on my computer anyway.

**Comment by EliteMasterEric** [comment]
Ah, I will have to try this later (I use a different IDE)
