### ISSUE TITLE
Custom Interiors?

### ISSUE THREAD

**Issue by Alyaqdhans** [x753/Lethal-Company-Mimics#23]
I'm trying to make the mod work on **PoolRooms** and **SewerFlow**, both of them have exit doors like the vanilla, but the mimics doesn't spawn on them

my whitelist:
`Level1Flow, Level1Flow3Exits, Level1FlowExtraLarge, Level2Flow, SDMLevel, OfficeDungeonFlow, TranquillityManorFlow, SewerFlow, PoolRooms`

Also, does the mod work for custom exit doors on modded interiors (ex: **CastleFlow** and **SchoolFlow**)? or only for vanilla looking doors?

**Comment by x753** [comment]
The mod only works for generic fire exits with a cutout in the wall behind them, or interiors that use the API if they want custom models for the doors (so far only Scarlet Devil Mansion). If you whitelisted them but they aren't spawning, it's probably because there isn't a cutout behind the door, blocking the mimic from spawning.
